build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
args:
  ZEROCLAW_VERSION: "0.6.9"
  AGENT_BROWSER_VERSION: "0.25.3"
  YQ_VERSION: "4.52.5"
